# Generated by Django 5.2.1 on 2025-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_app', '0001_initial'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='board_tasks', to='task_app.task'),
        ),
    ]
