# Generated by Django 5.2.1 on 2025-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_initial'),
        ('task_app', '0002_alter_task_comment'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_boards', to='user_auth_app.profile'),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='board_tasks', to='task_app.task'),
        ),
    ]
