# Generated by Django 5.2.1 on 2025-05-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_alter_board_members_alter_board_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
    ]
