# Generated by Django 5.2.1 on 2025-05-14 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_remove_board_tasks'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['owner'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='user_auth_app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board_members', to='user_auth_app.profile'),
        ),
    ]
