# Generated by Django 5.2.1 on 2025-05-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_remove_board_tasks'),
        ('task_app', '0002_alter_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board_app.board'),
        ),
    ]
