# Generated by Django 5.2.1 on 2025-05-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_alter_board_options_remove_board_owner_id_and_more'),
        ('task_app', '0008_alter_comment_options'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_task', to='user_auth_app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='user_auth_app.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='assigned_task', to='user_auth_app.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='board_app.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ManyToManyField(blank=True, related_name='reviewer_task', to='user_auth_app.profile'),
        ),
    ]
